### ISSUE TITLE
Variable spelled incorrectly 

### ISSUE THREAD

**Issue by Ali-Row** [dbilenkin/sadie-space-adventure-web#1]
Variable healthHight in game.js line 7 is spelt wrong, it should be healthHeight, OCD was killing me ;)

**Comment by dbilenkin** [comment]
Ha! Hey Alistair! I was not expecting an issue to be opened for this haha. My kid's in college learning python and I thought it would be fun to port the game they made over to JavaScript. 

I've fixed it now, take a look ;)

**Comment by Ali-Row** [comment]
Yeah I was just going through peoples repos and nosing around, this is a really cool project, I cloned it and had a go with it the other day! Anyways I hope you’ve been well Dimitri! 👍
